version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - data:/var/lib/mysql
      - ./initdb/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  backend:
      build:
        context: ./backend
      restart: always
      ports:
        - 8081:8080
      depends_on:
        - db

volumes:
  data:
